"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.getXataClient = exports.XataClient = void 0;
// Generated by Xata Codegen 0.29.4. Please do not edit.
const client_1 = require("@xata.io/client");
/** @typedef { import('./types').SchemaTables } SchemaTables */
/** @type { SchemaTables } */
const tables = [
  {
    name: "Users",
    columns: [
      { name: "Username", type: "string", unique: true },
      {
        name: "Password",
        type: "string",
        notNull: true,
        defaultValue: "user@123",
      },
      { name: "Email", type: "email", unique: true },
    ],
  },
  {
    name: "Dashboard",
    columns: [
      { name: "Username", type: "string", unique: true },
      { name: "Email", type: "email", unique: true },
      { name: "Contact", type: "string", unique: true },
      { name: "BloodGroup", type: "string" },
      { name: "MedicalHistory", type: "text" },
      { name: "Message", type: "text" },
      {
        name: "UserType",
        type: "string",
        notNull: true,
        defaultValue: "Donor",
      },
    ],
  },
];
/** @type { import('@xata.io/client').ClientConstructor<{}> } */
const DatabaseClient = (0, client_1.buildClient)();
const defaultOptions = {
  databaseURL:
    "https://appnichetechnologies-s-workspace-bbijnp.us-east-1.xata.sh/db/BloodBuddy",
};
/** @typedef { import('./types').DatabaseSchema } DatabaseSchema */
/** @extends DatabaseClient<DatabaseSchema> */
class XataClient extends DatabaseClient {
  constructor(options) {
    super({ ...defaultOptions, ...options }, tables);
  }
}
exports.XataClient = XataClient;
let instance = undefined;
/** @type { () => XataClient } */
const getXataClient = () => {
  if (instance) return instance;
  instance = new XataClient();
  return instance;
};
exports.getXataClient = getXataClient;
